title: NERO
description: Nonparametric Entropy-Rate Oracle. A model-agnostic approach for detecting LLM-generated text by estimating the entropy rate of text mapped to symbol streams over a (26+space)=27-letter alphabet.
theme: jekyll-theme-modernist
markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
